name: Testing chimerax

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
    build_wheels:
        name: Build wheels on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            # macos-13 is an intel runner, macos-14 is apple silicon
            os: [macos-latest, macos-15]
    
        steps:
          - uses: actions/checkout@v4
    
          # Used to host cibuildwheel
          - uses: actions/setup-python@v5
            with:
              python-version: 3.11
        
          - name: Install pyKVFinder
            run: |
                pip install pyKVFinder
                pip install pytest
                pytest --import-mode=importlib

